"""create table

Revision ID: 404fb4e6258a
Revises: 
Create Date: 2022-09-08 15:56:58.018242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404fb4e6258a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_developer_name'), 'developer', ['developer_name'], unique=True)
    op.create_table('story',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_name', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('calculated_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_calculated_time'), 'story', ['calculated_time'], unique=False)
    op.create_index(op.f('ix_story_story_name'), 'story', ['story_name'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('task_estimated_time', sa.Numeric(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('task_name', sa.String(length=64), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_end_date'), 'task', ['end_date'], unique=True)
    op.create_index(op.f('ix_task_iteration'), 'task', ['iteration'], unique=True)
    op.create_index(op.f('ix_task_start_date'), 'task', ['start_date'], unique=True)
    op.create_index(op.f('ix_task_task'), 'task', ['task'], unique=True)
    op.create_index(op.f('ix_task_task_estimated_time'), 'task', ['task_estimated_time'], unique=True)
    op.create_index(op.f('ix_task_task_name'), 'task', ['task_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_task_name'), table_name='task')
    op.drop_index(op.f('ix_task_task_estimated_time'), table_name='task')
    op.drop_index(op.f('ix_task_task'), table_name='task')
    op.drop_index(op.f('ix_task_start_date'), table_name='task')
    op.drop_index(op.f('ix_task_iteration'), table_name='task')
    op.drop_index(op.f('ix_task_end_date'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_story_story_name'), table_name='story')
    op.drop_index(op.f('ix_story_calculated_time'), table_name='story')
    op.drop_table('story')
    op.drop_index(op.f('ix_developer_developer_name'), table_name='developer')
    op.drop_table('developer')
    # ### end Alembic commands ###
