"""table

Revision ID: 861233fd1fcc
Revises: 85e2c80091a1
Create Date: 2022-09-07 15:01:49.279122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861233fd1fcc'
down_revision = '85e2c80091a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('total_time', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_story_total_time'), 'story', ['total_time'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_total_time'), table_name='story')
    op.drop_column('story', 'total_time')
    # ### end Alembic commands ###
