"""table

Revision ID: b02da714e258
Revises: dbc321bb781b
Create Date: 2022-09-07 15:16:18.244534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02da714e258'
down_revision = 'dbc321bb781b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('total_time', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_story_total_time'), 'story', ['total_time'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_total_time'), table_name='story')
    op.drop_column('story', 'total_time')
    # ### end Alembic commands ###
