"""stories tasks and developers tables

Revision ID: d8bc07f372cf
Revises: b3329efbb754
Create Date: 2022-09-09 10:53:14.867518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bc07f372cf'
down_revision = 'b3329efbb754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_name', sa.String(length=64), nullable=True))
    op.drop_index('ix_task_task', table_name='task')
    op.create_index(op.f('ix_task_task_name'), 'task', ['task_name'], unique=False)
    op.drop_column('task', 'task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_task_task_name'), table_name='task')
    op.create_index('ix_task_task', 'task', ['task'], unique=False)
    op.drop_column('task', 'task_name')
    # ### end Alembic commands ###
