"""table

Revision ID: dbc321bb781b
Revises: 861233fd1fcc
Create Date: 2022-09-07 15:02:53.084343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc321bb781b'
down_revision = '861233fd1fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_total_time', table_name='story')
    op.drop_column('story', 'total_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('total_time', sa.INTEGER(), nullable=True))
    op.create_index('ix_story_total_time', 'story', ['total_time'], unique=False)
    # ### end Alembic commands ###
