"""table

Revision ID: dc18ad7771bf
Revises: ec3f152a0b28
Create Date: 2022-09-07 15:17:50.011932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc18ad7771bf'
down_revision = 'ec3f152a0b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_total_time', table_name='story')
    op.drop_column('story', 'total_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('total_time', sa.INTEGER(), nullable=True))
    op.create_index('ix_story_total_time', 'story', ['total_time'], unique=False)
    # ### end Alembic commands ###
