"""table

Revision ID: ec3f152a0b28
Revises: b02da714e258
Create Date: 2022-09-07 15:17:38.952797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3f152a0b28'
down_revision = 'b02da714e258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('calculated_time', sa.Integer(), nullable=True))
    op.drop_index('ix_story_estimated_time', table_name='story')
    op.create_index(op.f('ix_story_calculated_time'), 'story', ['calculated_time'], unique=True)
    op.drop_column('story', 'estimated_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('estimated_time', sa.NUMERIC(), nullable=True))
    op.drop_index(op.f('ix_story_calculated_time'), table_name='story')
    op.create_index('ix_story_estimated_time', 'story', ['estimated_time'], unique=False)
    op.drop_column('story', 'calculated_time')
    # ### end Alembic commands ###
